// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';
// import type { Database } from './types';

// const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// let client: any;

// if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
//   // If env vars are missing, warn but do not throw so the dev UI can load.
//   // Provide a lightweight stub implementing a small subset of the Supabase
//   // client used by this app so the frontend can render during development.
//   console.warn(
//     'Supabase env missing: exporting stub supabase client. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to enable real Supabase.',
//     { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY }
//   );

//   const stubFrom = (table: string) => {
//     return {
//       select: (_sel?: any) => ({
//         eq: (_col: string, _val: any) => ({
//           single: async () => {
//             // Return a mock profile row when requesting profiles by id
//             if (table === 'profiles' && _col === 'id' && _val === 'mock-user') {
//               return {
//                 data: {
//                   id: 'mock-user',
//                   display_name: 'Gia Huy',
//                   avatar: '👤',
//                   school: '-',
//                   grade: '1',
//                   phone: '0392290338',
//                   email: 'hoangquockhanh204@gmail.com',
//                   address: null,
//                   dob: null,
//                 },
//                 error: null,
//               };
//             }
//             return { data: null, error: null };
//           },
//         }),
//         single: async () => ({ data: null, error: null }),
//       }),
//       update: (_payload: any) => ({
//         eq: (_col: string, _val: any) => ({
//           select: () => ({ single: async () => ({ data: _payload, error: null }) }),
//         }),
//       }),
//       insert: async (_payload: any) => ({ data: null, error: null }),
//     };
//   };

//   client = {
//     auth: {
//       getSession: async () => ({ data: { session: { user: { id: 'mock-user' } } } }),
//       signOut: async () => ({ error: null }),
//       resetPasswordForEmail: async (_email: string, _opts?: any) => ({ error: null }),
//     },
//     from: stubFrom,
//     storage: {
//       from: () => ({ upload: async () => ({ error: null, data: null }) }),
//     },
//   };
// } else {
//   client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//     auth: {
//       // use the browser localStorage; if you run any SSR routes remove this option
//       storage: typeof window !== 'undefined' ? window.localStorage : undefined,
//       persistSession: true,
//       autoRefreshToken: true,
//     },
//   });
// }

// export const supabase = client;

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});